# Generated by Django 2.1.dev20180328172503 on 2018-03-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='IMAGE',
            field=models.FileField(blank=True, null=True, upload_to='universities/'),
        ),
    ]
