# Generated by Django 2.1.dev20180328172503 on 2018-03-30 13:06

from django.db import migrations, models
import universities.models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to=universities.models.upload_image_path),
        ),
    ]
