# Generated by Django 2.1.dev20180328172503 on 2018-03-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_auto_20180330_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='IMAGE',
            new_name='image',
        ),
    ]
