# Generated by Django 2.1.dev20180328172503 on 2018-04-02 15:16

from django.db import migrations, models
import programmes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=programmes.models.upload_image_path)),
                ('fee', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
            ],
        ),
    ]
