# Generated by Django 2.1.dev20180328172503 on 2018-04-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180404_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='username',
            new_name='user',
        ),
    ]
