# Generated by Django 2.0.1 on 2018-04-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_a',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_b',
        ),
    ]
