# Generated by Django 2.0.1 on 2018-04-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180405_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_a',
            new_name='is_student',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_b',
            new_name='is_teacher',
        ),
    ]
